export const currentUser = {
  id: 'demo-user',
  username: 'maya',
  display_name: 'Maya Chen',
  avatar_url: null,
};

export const mockAnnotations = [
  {
    id: 'I6KyT-Ah5Wna',
    user_id: 'hZTIgPwtkZPF',
    username: 'jason',
    display_name: 'Jason Calacanis',
    avatar_url: null,
    source_url: 'https://www.theverge.com/ai-agents-browser',
    source_title: 'AI Agents Are Reshaping How We Use the Web',
    source_type: 'article',
    source_domain: 'theverge.com',
    source_thumbnail: null,
    clip_text: 'The shift from chatbots to agentic workflows changes the browser from a destination into a command surface.',
    clip_start_sec: null,
    clip_end_sec: null,
    clip_media_path: null,
    commentary: 'This is the part everyone keeps underestimating. The interface layer is moving from pages to intent, which means distribution gets weird very quickly.',
    is_public: 1,
    pin_count: 18,
    comment_count: 9,
    like_count: 142,
    liked: false,
    pinned: true,
    created_at: '2026-05-10 07:08:15',
    updated_at: '2026-05-10 07:08:15',
  },
  {
    id: 'Z0p-clip-thread',
    user_id: '7kLmz',
    username: 'nadia',
    display_name: 'Nadia Patel',
    avatar_url: null,
    source_url: 'https://www.youtube.com/watch?v=demo',
    source_title: 'Why Great Interfaces Feel Inevitable',
    source_type: 'youtube',
    source_domain: 'youtube.com',
    source_thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=320&q=80',
    clip_text: null,
    clip_start_sec: 612,
    clip_end_sec: 676,
    clip_media_path: null,
    commentary: 'The useful framing here is that delight is usually the last 10 percent of latency, copy, and layout all clicking at once.',
    is_public: 1,
    pin_count: 7,
    comment_count: 14,
    like_count: 88,
    liked: true,
    pinned: false,
    created_at: '2026-05-10 05:42:00',
    updated_at: '2026-05-10 05:42:00',
  },
  {
    id: 'podcast-signal-42',
    user_id: 'p0dcast',
    username: 'elliot',
    display_name: 'Elliot Reeves',
    avatar_url: null,
    source_url: 'https://example.com/podcasts/media-economics',
    source_title: 'Media Economics After the Feed',
    source_type: 'podcast',
    source_domain: 'example.com',
    source_thumbnail: null,
    clip_text: null,
    clip_start_sec: 1842,
    clip_end_sec: 1918,
    clip_media_path: null,
    commentary: 'The strongest platforms let people argue with the source material in public. That is a different product than saving things for later.',
    is_public: 1,
    pin_count: 3,
    comment_count: 5,
    like_count: 61,
    liked: false,
    pinned: false,
    created_at: '2026-05-09 21:19:00',
    updated_at: '2026-05-09 21:19:00',
  },
];

export const mockComments = [
  {
    id: 'c1',
    username: 'rachel',
    display_name: 'Rachel Kim',
    avatar_url: null,
    body: 'The browser-as-command-surface point feels especially right for research. I do not want ten tabs; I want a trail of claims I can inspect.',
    created_at: '2026-05-10 08:04:00',
    replies: [
      {
        id: 'c1-r1',
        username: 'marco',
        display_name: 'Marco Silva',
        avatar_url: null,
        body: 'Exactly. The audit trail matters more than the magic trick.',
        created_at: '2026-05-10 08:12:00',
        replies: [
          {
            id: 'c1-r1-a',
            username: 'maya',
            display_name: 'Maya Chen',
            avatar_url: null,
            body: 'And it makes commentary portable, which is the missing social primitive.',
            created_at: '2026-05-10 08:16:00',
            replies: [],
          },
        ],
      },
      {
        id: 'c1-r2',
        username: 'tal',
        display_name: 'Tal Rosen',
        avatar_url: null,
        body: 'There is also a huge trust angle here. If the agent summarizes without the quote, the debate gets slippery.',
        created_at: '2026-05-10 08:22:00',
        replies: [],
      },
    ],
  },
  {
    id: 'c2',
    username: 'ina',
    display_name: 'Ina Morales',
    avatar_url: null,
    body: 'Feels like the first durable social graph for this is people who consistently identify the important passage, not just the important link.',
    created_at: '2026-05-10 08:37:00',
    replies: [],
  },
];

export const mockUser = {
  id: 'hZTIgPwtkZPF',
  username: 'jason',
  display_name: 'Jason Calacanis',
  avatar_url: null,
  bio: 'Investor, reader, and occasional media firestarter. Annotating the internet in public.',
  stats: {
    annotations: 128,
    followers: 24800,
    following: 312,
  },
  following: false,
};
