export const currentUser = {
  id: 'demo-user',
  username: 'maya',
  display_name: 'Maya Desai',
  avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=96&q=80',
};

export const mockUsers = [
  {
    id: 'hZTIgPwtkZPF',
    username: 'mayadesai',
    display_name: 'Maya Desai',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=96&q=80',
    bio: 'Editor, policy reader, and collector of sentences that explain more than they should.',
    stats: { annotations: 128, followers: 24800, following: 312 },
    following: false,
  },
  {
    id: 'jonah',
    username: 'jonahlee',
    display_name: 'Jonah Lee',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=96&q=80',
    bio: 'Writing about memory, attention, and the technologies that keep both under pressure.',
    stats: { annotations: 83, followers: 9400, following: 190 },
    following: true,
  },
  {
    id: 'leila',
    username: 'leilahaddad',
    display_name: 'Leila Haddad',
    avatar_url: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=96&q=80',
    bio: 'Foreign policy notes, energy maps, and the occasional sentence worth arguing with.',
    stats: { annotations: 54, followers: 7200, following: 144 },
    following: false,
  },
  {
    id: 'david',
    username: 'davidng',
    display_name: 'David Ng',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=96&q=80',
    bio: 'Economics editor watching AI discourse become labor discourse in real time.',
    stats: { annotations: 67, followers: 11800, following: 203 },
    following: false,
  },
];

export const mockAnnotations = [
  {
    id: 'I6KyT-Ah5Wna',
    user_id: 'hZTIgPwtkZPF',
    username: 'mayadesai',
    display_name: 'Maya Desai',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=96&q=80',
    source_url: 'https://www.ft.com/global-economy-resilience',
    source_title: 'Why the global economy keeps defying the pessimists',
    source_type: 'article',
    source_domain: 'ft.com',
    source_thumbnail: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=480&q=80',
    clip_text: 'The resilience of consumer spending, the adaptability of businesses and the gradual easing of inflationary pressures have combined to produce outcomes that many forecasters did not anticipate.',
    clip_start_sec: null,
    clip_end_sec: null,
    clip_media_path: null,
    commentary: 'Pessimism sells, but it is not a strategy. The real story is adaptation: boring, decentralized and unglamorous.',
    is_public: 1,
    pin_count: 8,
    comment_count: 8,
    like_count: 42,
    liked: false,
    pinned: false,
    created_at: '2026-05-10 07:08:15',
    updated_at: '2026-05-10 07:08:15',
  },
  {
    id: 'forgetting-thread',
    user_id: 'jonah',
    username: 'jonahlee',
    display_name: 'Jonah Lee',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=96&q=80',
    source_url: 'https://aeon.co/essays/the-case-for-forgetting',
    source_title: 'The case for forgetting in a world that never stops recording',
    source_type: 'article',
    source_domain: 'aeon.co',
    source_thumbnail: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=480&q=80',
    clip_text: 'Memory, we think, makes us who we are. But forgetting is also an essential part of the human condition, shaping our health, our relationships and even our capacity for creativity.',
    clip_start_sec: null,
    clip_end_sec: null,
    clip_media_path: null,
    commentary: 'We romanticize memory and pathologize forgetting. But forgetting is not failure, it is a form of self-preservation.',
    is_public: 1,
    pin_count: 6,
    comment_count: 6,
    like_count: 35,
    liked: true,
    pinned: false,
    created_at: '2026-05-10 04:42:00',
    updated_at: '2026-05-10 04:42:00',
  },
  {
    id: 'minerals-map',
    user_id: 'leila',
    username: 'leilahaddad',
    display_name: 'Leila Haddad',
    avatar_url: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=96&q=80',
    source_url: 'https://foreignaffairs.com/critical-minerals',
    source_title: 'The new geopolitics of critical minerals',
    source_type: 'article',
    source_domain: 'foreignaffairs.com',
    source_thumbnail: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=480&q=80',
    clip_text: 'Control over lithium, cobalt and rare earths is the defining resource competition of the 21st century.',
    clip_start_sec: null,
    clip_end_sec: null,
    clip_media_path: null,
    commentary: 'Energy security was yesterday. The mineral map will redraw the alliances of tomorrow.',
    is_public: 1,
    pin_count: 4,
    comment_count: 4,
    like_count: 28,
    liked: false,
    pinned: false,
    created_at: '2026-05-09 15:30:00',
    updated_at: '2026-05-09 15:30:00',
  },
  {
    id: 'ai-not-obsolete',
    user_id: 'david',
    username: 'davidng',
    display_name: 'David Ng',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=96&q=80',
    source_url: 'https://www.economist.com/ai-work-human-value',
    source_title: 'AI will not make us obsolete',
    source_type: 'youtube',
    source_domain: 'economist.com',
    source_thumbnail: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=480&q=80',
    clip_text: null,
    clip_start_sec: 312,
    clip_end_sec: 371,
    clip_media_path: null,
    commentary: 'The question is not man or machine. It is which humans we choose to become.',
    is_public: 1,
    pin_count: 7,
    comment_count: 7,
    like_count: 31,
    liked: false,
    pinned: false,
    created_at: '2026-05-09 12:05:00',
    updated_at: '2026-05-09 12:05:00',
  },
];

export const mockComments = [
  {
    id: 'c1',
    username: 'rachel',
    display_name: 'Rachel Kim',
    avatar_url: null,
    body: 'The adaptation point is exactly what gets missed in daily coverage. It is not dramatic enough to trend, but it compounds.',
    created_at: '2026-05-10 08:04:00',
    replies: [
      {
        id: 'c1-r1',
        username: 'marco',
        display_name: 'Marco Silva',
        avatar_url: null,
        body: 'Right. We keep looking for a single heroic intervention when the story is thousands of small adjustments.',
        created_at: '2026-05-10 08:12:00',
        replies: [
          {
            id: 'c1-r1-a',
            username: 'maya',
            display_name: 'Maya Desai',
            avatar_url: null,
            body: 'And that is why the source quote matters. It grounds the optimism in boring operating reality.',
            created_at: '2026-05-10 08:16:00',
            replies: [],
          },
        ],
      },
    ],
  },
  {
    id: 'c2',
    username: 'ina',
    display_name: 'Ina Morales',
    avatar_url: null,
    body: 'This is also a good example of why annotations need the clip attached. The take is stronger because you can inspect the claim.',
    created_at: '2026-05-10 08:37:00',
    replies: [],
  },
];

export const mockUser = {
  ...mockUsers[0],
};
